// <auto-generated />
using System;
using AlloHonda.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlloHonda.Migrations
{
    [DbContext(typeof(AlloHondaContext))]
    [Migration("20251227000329_initialmigration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlloHanda.Models.Chauffeur", b =>
                {
                    b.Property<int>("IdChauffeur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChauffeur"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdChauffeur");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Chauffeur");
                });

            modelBuilder.Entity("AlloHanda.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdClient");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Client");
                });

            modelBuilder.Entity("AlloHanda.Models.DemandeTransport", b =>
                {
                    b.Property<int>("IdDemande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDemande"));

                    b.Property<int?>("ChauffeurId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionMarchandise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Poids")
                        .HasColumnType("float");

                    b.Property<double>("PrixEstime")
                        .HasColumnType("float");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDemande");

                    b.HasIndex("ChauffeurId");

                    b.HasIndex("ClientId");

                    b.ToTable("DemandeTransport");
                });

            modelBuilder.Entity("AlloHanda.Models.Trajet", b =>
                {
                    b.Property<int>("IdTrajet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTrajet"));

                    b.Property<string>("AdresseArrivee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdresseDepart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DemandeTransportId")
                        .HasColumnType("int");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<double>("DureeEstimee")
                        .HasColumnType("float");

                    b.HasKey("IdTrajet");

                    b.HasIndex("DemandeTransportId")
                        .IsUnique();

                    b.ToTable("Trajet");
                });

            modelBuilder.Entity("AlloHanda.Models.Vehicule", b =>
                {
                    b.Property<int>("IdVehicule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVehicule"));

                    b.Property<double>("Capacite")
                        .HasColumnType("float");

                    b.Property<int>("ChauffeurId")
                        .HasColumnType("int");

                    b.Property<string>("Immatriculation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVehicule");

                    b.HasIndex("ChauffeurId")
                        .IsUnique();

                    b.ToTable("Vehicule");
                });

            modelBuilder.Entity("AlloHonda.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PhotoProfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUser");
                });

            modelBuilder.Entity("AlloHanda.Models.Chauffeur", b =>
                {
                    b.HasOne("AlloHonda.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Chauffeur")
                        .HasForeignKey("AlloHanda.Models.Chauffeur", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("AlloHanda.Models.Client", b =>
                {
                    b.HasOne("AlloHonda.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Client")
                        .HasForeignKey("AlloHanda.Models.Client", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("AlloHanda.Models.DemandeTransport", b =>
                {
                    b.HasOne("AlloHanda.Models.Chauffeur", "Chauffeur")
                        .WithMany("DemandesAcceptees")
                        .HasForeignKey("ChauffeurId");

                    b.HasOne("AlloHanda.Models.Client", "Client")
                        .WithMany("Demandes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chauffeur");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AlloHanda.Models.Trajet", b =>
                {
                    b.HasOne("AlloHanda.Models.DemandeTransport", "DemandeTransport")
                        .WithOne("Trajet")
                        .HasForeignKey("AlloHanda.Models.Trajet", "DemandeTransportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemandeTransport");
                });

            modelBuilder.Entity("AlloHanda.Models.Vehicule", b =>
                {
                    b.HasOne("AlloHanda.Models.Chauffeur", "Chauffeur")
                        .WithOne("Vehicule")
                        .HasForeignKey("AlloHanda.Models.Vehicule", "ChauffeurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chauffeur");
                });

            modelBuilder.Entity("AlloHanda.Models.Chauffeur", b =>
                {
                    b.Navigation("DemandesAcceptees");

                    b.Navigation("Vehicule")
                        .IsRequired();
                });

            modelBuilder.Entity("AlloHanda.Models.Client", b =>
                {
                    b.Navigation("Demandes");
                });

            modelBuilder.Entity("AlloHanda.Models.DemandeTransport", b =>
                {
                    b.Navigation("Trajet")
                        .IsRequired();
                });

            modelBuilder.Entity("AlloHonda.Models.ApplicationUser", b =>
                {
                    b.Navigation("Chauffeur")
                        .IsRequired();

                    b.Navigation("Client")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
